import * as THREE from 'three';
import {findHomePlace,presetName,searchText} from './view-presets.js?v=1.4';
import {nearestNetworkPoint} from './network-walk.js?v=1.4';
import {serializeProject} from './data.js?v=1.4';
const $=id=>document.getElementById(id);
export const LAYERS={restaurantes:'Restaurantes',piscinas:'Piscinas',habitaciones:'Habitaciones',servicios:'Servicios',rutas:'Rutas',accesibilidad:'Accesibilidad'};
export function placeLayer(place){const c=searchText(place.category);return place.accessible||/accesibilidad|accessible/.test(c)?'accesibilidad':/restaurante|restaurant|bar/.test(c)?'restaurantes':/piscina|pool/.test(c)?'piscinas':/edificio|habitacion|room/.test(c)?'habitaciones':'servicios';}
export function modelKey(project){let h=2166136261;const add=s=>{for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}};add(project.name);for(const o of project.objects){add(o.id);add(o.position);add(o.scale);}const network=project.network.sourceNetwork||project.network;for(const n of network.nodes){add(n.id);add(n.position);}for(const e of network.edges){add(e.id);add(e.a);add(e.b);}return (h>>>0).toString(36);}
export function sharedView(search){const q=new URLSearchParams(search),place=q.get('place'),x=q.has('x')?Number(q.get('x')):NaN,z=q.has('z')?Number(q.get('z')):NaN;return place?{place:place.slice(0,120),model:q.get('model')}:Number.isFinite(x)&&Number.isFinite(z)&&Math.abs(x)<=1e6&&Math.abs(z)<=1e6?{position:[x,0,z],model:q.get('model')}:null;}
export class JourneyUI {
  constructor(api,arrival){
    this.api=api;this.viewer=api.viewer;this.walk=api.walk;this.explorer=api.explorer;this.arrival=arrival;this.history=[];this.layers=Object.fromEntries(Object.keys(LAYERS).map(k=>[k,true]));this.query='';this.pendingShare=sharedView(location.search);
    $('changeArrival').addEventListener('click',async()=>{if(api.busy())return;this.walk.resetInput();this.walk.suspended=true;const before=arrival.current?.id;await arrival.open();this.walk.suspended=false;$('changeArrival').textContent=arrival.label;if(arrival.current.id!==before){this.remember();if(this.walk.active)api.closeWalk();this.applyHome(true);}});
    $('historyBack').addEventListener('click',()=>this.back());$('shareView').addEventListener('click',()=>this.share());$('closeShare').addEventListener('click',()=>$('shareDialog').close());
    $('shareDialog').addEventListener('close',()=>{this.walk.suspended=api.busy();this.walk.resetInput();});
    $('copyViewLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('viewLink').value);api.toast('Enlace copiado.');}catch{$('viewLink').focus();$('viewLink').select();api.toast('Selecciona Copiar en el campo del enlace.');}});
    $('downloadPublishedMap').addEventListener('click',()=>{if(this.explorer.role!=='editor')return;const url=URL.createObjectURL(new Blob([JSON.stringify(serializeProject(this.project),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='mapa.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);api.toast('Sube mapa.json al lado de index.html para que el enlace también abra tu maqueta.');});
    $('placeSearch').addEventListener('input',()=>{this.query=searchText($('placeSearch').value);this.explorer.refreshPlaces();});
    $('enterPlace').addEventListener('click',()=>this.enter(this.explorer.selectedPlace));
    $('lookAtDestination').addEventListener('click',()=>{const place=this.explorer.destination||this.explorer.selectedPlace;if(!place){api.toast('Elige primero un destino.');return;}this.walk.active?this.walk.lookToward(place.position):this.viewer.lookToward(place.position);});
    $('layerToggle').addEventListener('click',()=>{$('layerPanel').hidden=!$('layerPanel').hidden;$('layerToggle').setAttribute('aria-expanded',String(!$('layerPanel').hidden));});
    for(const [key,label]of Object.entries(LAYERS)){const row=document.createElement('label'),check=document.createElement('input'),name=document.createElement('span');check.type='checkbox';check.checked=true;check.setAttribute('aria-label',label);name.textContent=label;row.append(check,name);check.addEventListener('change',()=>{this.layers[key]=check.checked;this.applyLayers();});$('layerList').append(row);}
    this.explorer.placeFilter=p=>this.layers[placeLayer(p)]&&(!this.query||searchText(`${p.name} ${p.id} ${p.category} ${p.description}`).includes(this.query));
    this.explorer.pins.filter=p=>this.layers[placeLayer(p)];this.explorer.minimap.filter=p=>this.layers[placeLayer(p)];
    for(const id of ['aheadStyle','walkAheadStyle'])$(id).addEventListener('change',()=>this.setStyle($(id).value));
    $('useOrigin').addEventListener('click',()=>{if(!this.holdPoint)return;const location=nearestNetworkPoint(this.project.network,this.holdPoint);if(!location){api.toast('Esta maqueta aún no tiene caminos.');return;}const origin={id:'custom-origin',name:'Desde aquí',position:location.position,accessPosition:location.position,location,accessDistance:0};api.setOrigin(origin);$('originMenu').hidden=true;$('originHint').textContent='Origen elegido. Ahora toca un lugar o elige Hacia.';$('originHint').hidden=false;api.toast(location.distance>this.viewer.baseEyeHeight?`Origen colocado sobre el camino más cercano, a ${location.distance.toFixed(1)} m del punto señalado. Ahora elige un destino.`:'Origen elegido. Ahora elige tu destino.');});
    $('cancelOrigin').addEventListener('click',()=>$('originMenu').hidden=true);this.bindHold();
  }
  setProject(project){this.project=project;this.history=[];this.focusedPlace=null;this.query='';$('placeSearch').value='';$('homeStatus').textContent='Carga tu maqueta para ubicar el edificio que elegiste.';$('originHint').hidden=true;$('originMenu').hidden=true;this.setStyle(project.explorer?.aheadStyle||'line',false);this.applyLayers();this.applyHome(false);this.updateHistory();$('changeArrival').textContent=this.arrival.label;$('shareView').disabled=!project.objects.length;
    if(project.objects.length&&this.pendingShare){if(this.pendingShare.model&&this.pendingShare.model!==modelKey(project)){this.api.toast('Este enlace corresponde a otra maqueta. Carga el mismo archivo para abrir esa vista.');return;}const place=project.places.find(p=>p.id===this.pendingShare.place&&p.visible),point=this.pendingShare.position;if(place){this.viewer.focusPoint(place.position,null,false);this.focusedPlace=place;this.explorer.openPlace(place);}else if(point){this.viewer.focusPoint(point,null,false);}else this.api.toast('El lugar del enlace no está en esta maqueta.');this.pendingShare=null;}
  }
  applyHome(smooth=false,resetOrigin=true){
    const preset=this.arrival.current;if(!preset||!this.project?.objects.length)return;const center=this.project.viewCenters?.find(c=>c.id===preset.id),place=findHomePlace(this.project,preset),destination=place&&this.api.destinations().find(d=>d.id===place.id);
    if(center){this.viewer.focusPoint(center.position,center.initialView,smooth);const canonical=this.project.network.nodeAliases?.[center.nearestRouteNodeId]||center.nearestRouteNodeId,node=this.project.network.nodes.find(n=>n.id===canonical),point=node?.position||center.position,location=nearestNetworkPoint(this.project.network,point);if(location&&resetOrigin)this.api.setOrigin({id:'home-origin',name:`${presetName(preset)} · Inicio`,position:center.position,accessPosition:location.position,location,accessDistance:location.distance},smooth);}
    else if(place){this.viewer.focusPoint(place.position,null,smooth);this.focusedPlace=place;if(destination&&resetOrigin)this.api.setOrigin(destination,smooth);}
    else if(smooth)this.api.toast(`Aún no hay un centrador para ${presetName(preset)} en esta maqueta.`);
    $('homeStatus').textContent=center?'Tu vista inicial y origen están en este edificio.':place?'Vista inicial localizada por su marcador.':'Carga una maqueta con el centrador de este edificio para ubicar tu inicio.';return !!(center||place);
  }
  remember(){if(!this.project?.objects.length)return;this.history.push({view:this.viewer.captureView(),walk:this.walk.captureState(),route:this.api.route(),progress:this.api.routeVisual.progress,destination:this.explorer.destination,place:this.focusedPlace});if(this.history.length>12)this.history.shift();this.updateHistory();}
  updateHistory(){$('historyBack').disabled=!this.history.length;}
  back(){if(this.api.busy())return;const state=this.history.pop();if(!state)return;if(this.walk.active)this.api.closeWalk();this.api.restoreRoute(state.route,state.progress);if(state.walk)this.api.restoreWalk(state.walk);else this.viewer.restoreView(state.view);this.explorer.setDestination(state.destination);this.focusedPlace=state.place;this.explorer.closePlace();this.updateHistory();}
  quickVisit(place){if(this.api.busy()||!place)return;this.remember();if(this.walk.active)this.api.closeWalk();this.viewer.focusPoint(place.position);this.focusedPlace=place;this.explorer.openPlace(place);$('placeSearch').blur();}
  enter(place){if(!place||this.api.busy())return;const location=nearestNetworkPoint(this.project.network,place.position);if(!location){this.api.toast('Este lugar todavía no tiene un camino para entrar.');return;}this.remember();if(this.walk.active)this.api.closeWalk();this.api.startFree(location);this.focusedPlace=place;if(location.distance>this.viewer.baseEyeHeight)this.api.toast(`Entraste en el acceso más cercano a ${place.name}, a ${location.distance.toFixed(1)} m en línea recta.`);}
  applyLayers(){this.explorer.refreshPlaces();this.explorer.pins.update();this.explorer.minimap.showRoutes=this.layers.rutas;this.api.routeVisual.group.visible=this.layers.rutas;this.viewer.dirty=true;}
  setStyle(style,edited=true){if(edited&&this.explorer.role!=='editor')return;const value=style==='breadcrumbs'?'breadcrumbs':'line';if(this.project)this.project.explorer={...this.project.explorer,aheadStyle:value};for(const id of ['aheadStyle','walkAheadStyle'])$(id).value=value;this.api.routeVisual.setStyle(value);if(edited)$('editStatus').hidden=false;}
  share(){if(!this.project?.objects.length)return;this.walk.resetInput();this.walk.suspended=true;const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('map',this.api.isDemo()?'demo':'published');url.searchParams.set('model',modelKey(this.project));const place=this.explorer.selectedPlace;const point=this.walk.active?this.walk.currentPoint:this.viewer.controls.target.toArray();if(place)url.searchParams.set('place',place.id);else{url.searchParams.set('x',point[0].toFixed(4));url.searchParams.set('z',point[2].toFixed(4));}$('viewLink').value=url.href;$('shareNote').textContent=this.api.isDemo()?'Este enlace abre la maqueta de ejemplo en la zona elegida.':'El enlace guarda la zona. Para abrir también tu maqueta, sube mapa.json al repositorio. Si no está publicado, la otra persona tendrá que cargar el mismo JSON.';$('downloadPublishedMap').hidden=this.api.isDemo();$('shareDialog').showModal();}
  bindHold(){
    const canvas=this.viewer.renderer.domElement,pointers=new Set();let hold=null,timer=null;const cancel=()=>{clearTimeout(timer);hold=null;};
    canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);cancel();$('originMenu').hidden=true;if(pointers.size!==1||e.button!==0||this.walk.active||this.api.busy()||this.explorer.pins.onPlacePosition)return;hold={id:e.pointerId,x:e.clientX,y:e.clientY};timer=setTimeout(()=>{if(!hold||pointers.size!==1)return;this.explorer.pins.down=null;const rect=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();this.viewer.camera.updateMatrixWorld();ray.setFromCamera(new THREE.Vector2((hold.x-rect.left)/rect.width*2-1,-(hold.y-rect.top)/rect.height*2+1),this.viewer.camera);const point=new THREE.Vector3();if(!ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),point))return;this.holdPoint=point.toArray();$('originMenu').hidden=false;const width=this.viewer.container.clientWidth,height=this.viewer.container.clientHeight;$('originMenu').style.left=`${Math.max(8,Math.min(width-220,hold.x-rect.left-100))}px`;$('originMenu').style.top=`${Math.max(20,Math.min(height-150,hold.y-rect.top-70))}px`;},620);},{capture:true});
    canvas.addEventListener('pointermove',e=>{if(hold&&hold.id===e.pointerId&&Math.hypot(e.clientX-hold.x,e.clientY-hold.y)>8)cancel();},{capture:true});
    for(const event of ['pointerup','pointercancel','lostpointercapture'])window.addEventListener(event,e=>{pointers.delete(e.pointerId);if(hold?.id===e.pointerId)cancel();});window.addEventListener('blur',()=>{cancel();pointers.clear();});
  }
}
